"""empty message

Revision ID: 060849bf3720
Revises: 
Create Date: 2023-05-22 15:46:58.604983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060849bf3720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fridge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_date', sa.Date(), nullable=True))
        batch_op.drop_column('exp_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fridge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_data', sa.DATE(), nullable=True))
        batch_op.drop_column('exp_date')

    # ### end Alembic commands ###
